export class Phone {
    id_phone!: number;
    marque!: string;
    model!: string;
    Qte!: number;
    year!:number;
    prix!: number;
    promo!: number;
    rom!: number;
    ram!: number;
    sim!: number;
    ecran_type!: string;
    ecran_taille!: string;
    ecran_resolution!: string;
    systeme!: string;
    processeur!: string;
    camera_front!: string;
    camera!: string;
    flash_arriere!: string;
    video!: string;
    connectivite!: string;
    capteur!: string;
    batteri!: string;
    charge!: number;
    reseau!: string;
    image!: string;
    note!: number;
    mention!: string;
    comment!: string;
    version?: string;
}